### ISSUE TITLE
test for 'require' throwing error when using Loader

### ISSUE THREAD

**Issue by tphdev** [TIY-Houston-Front-End-Engineering/777-Browserify#1]
Hey Matt,

My first 'issue'....

When loading scripts from app.js and Loader instead of modules,  the code breaks when testing for `require` on **line 10** in the **777.js** file:

``` js
if(require)
```

It throws a Reference Error, saying that 'require is not defined`

I believe this is happening due to `require` not being previously _declared_ anywhere when using the app.js scripts--i.e. no modules. I'm sure you've seen this before, but I got the test-for-require to work by using a `typeof` test.  

In this case: i changed **line 10** in the _777.js_ file  to:

``` js
if( typeof require != 'undefined' )
```

**Comment by matthiasak** [comment]
Good find @t3patterson
